server:
  port: 8082

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/hotel_booking
    username: dev
    password: '123456@'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      enabled: true  # bật lại
  config:
    import: optional:configserver:http://config-server:8888/

logging:
  level:
    org.springframework.security: DEBUG
